
# Sanitize ( very destructive) + telemetry heavy

controllers:
  explicit: ["/dev/nvme1"]
namespaces:
  explicit: ["/dev/nvme1n1"]

sanitize:
  enabled: true
  action: "crypto"
  ause: true
  interval: 10
  timeout: 3600

telemetry:
  sensors_interval: 1
  turbostat_interval: 1
  nvme_telemetry: true
  power_interval: 1
