# NVMe QA Config (example)
output_dir: ./nvme_reports

controllers:
  explicit:
    - /dev/nvme1
  include_regex: ".*"
  exclude_regex: ""

namespaces:
  explicit:
    - /dev/nvme1n1
  include_regex: ".*"
  exclude_regex: ""

smart:
  duration: 30      # seconds to monitor SMART during workload
  interval: 5       # SMART sampling interval (sec)

fio:
  runtime: 20       # seconds per workload
  iodepth: 4
  bs: "4k"
  ioengine: "io_uring"
  workloads: ["randread", "randwrite"]

filesystem:
  create: true
  type: ext4
  mkfs_options: "-F"
  mount: true
  mount_base: /mnt/nvmeqa
  mount_options: "defaults,noatime"
  fio_on_fs: true
  fio_file_size: "8G"
  fio_file_prefix: "fio_nvmeqa"

format:
  enabled: false    # set true if you want auto-format before test
  lbaf: 0
  ses: 0
  wait_after: 5

sanitize:
  enabled: false    # set true for nvme sanitize operation
  action: "none"    # options: none, block, overwrite, crypto
  ause: true
  owpass: 1
  interval: 5
  timeout: 1800

write_protect:
  enabled: false
  value: 1

telemetry:
  sensors_interval: 2
  turbostat_interval: 2
  nvme_telemetry: true
  power_interval: 2
