
# Discovery filters

controllers:
  explicit: ["/dev/nvme1", "/dev/nvme2"]   # prefer explicit if provided
  include_regex: ".*"                      # regex applied to derived controllers
  exclude_regex: ""                        # regex to exclude derived controllers

namespaces:
  explicit: ["/dev/nvme1n1"]               # prefer explicit if provided
  include_regex: ".*"
  exclude_regex: ""
