
# Multiple controllers/namespaces, with formatting ( destructive)

controllers:
  explicit: ["/dev/nvme0", "/dev/nvme1"]

namespaces:
  explicit: ["/dev/nvme0n1", "/dev/nvme1n1"]

format:
  enabled: true
  lbaf: 0
  ses: 0
  wait_after: 5

filesystem:
  create: true
  type: xfs
  mkfs_options: "-f"
  mount: true
  mount_base: /mnt/nvmeqa
  fio_on_fs: true
  fio_file_size: "16G"

fio:
  runtime: 30
  iodepth: 8
  bs: "4k"
  workloads: ["randread", "randwrite"]
