
output_dir: ./nvme_reports

smart: { duration: 45, interval: 5 }

fio:
  runtime: 45
  iodepth: 8
  bs: 4k
  ioengine: io_uring
  workloads: [randread, randwrite]

# Choose controllers explicitly (optional)
controllers:
  explicit: [ "/dev/nvme1"]   # <- test only these controllers
  include_regex: ".*"
  exclude_regex: ""

# Or choose namespaces explicitly (optional)
namespaces:
  explicit: ["/dev/nvme1n1"]               # <- test only this namespace (per matching controller)
  include_regex: ".*"
  exclude_regex: ""

# Destructive ops (off by default)
sanitize: { enabled: false, action: "none" }
format:   { enabled: false, lbaf: 0, ses: 0 }

write_protect: { enabled: false, value: 1 }

filesystem:
  create: true
  type: ext4
  mkfs_options: "-F"
  mount: true
  mount_base: "/mnt/nvmeqa"
  mount_options: "defaults,noatime"
  fio_on_fs: true
  fio_file_size: "8G"
  fio_file_prefix: "fio_nvmeqa"

telemetry:
  sensors_interval: 2
  turbostat_interval: 2
  nvme_telemetry: true
  power_interval: 2
